### ISSUE TITLE
Some mobile phone have a exception when take a picture。

### ISSUE THREAD

**Issue by 81813780** [jaydeepw/poly-picker#22]
Some mobile phone have a exception when take a picture。
 java.lang.IllegalStateException: Unable to create new file: /storage/sdcard0/DCIM/Camera/1418805137509.jpg

cause this code :String path = MediaStore.Images.Media.insertImage(getActivity().getContentResolver(), bitmap, getPhotoFilename(), null);

I think this exception maybe with  some mobile phone sdcard path diffenrent

could you help me to solve this question, thanks a lot.

**Comment by jaydeepw** [comment]
I tested the sample app that uses the latest version (vv1.0.11 at the time of writing) on Mi Redmi and found it working flawlessly. Anything specific I should do to reproduce the crash?

Let me know, I will close the issue otherwise.
