### ISSUE TITLE
Add Support for Material Sliding Tabs to Support AppCompat Themes

### ISSUE THREAD

**Issue by vivekkiran** [jaydeepw/poly-picker#44]
http://www.android4devs.com/2015/01/how-to-make-material-design-sliding-tabs.html
http://www.exoguru.com/android/material-design/navigation/android-sliding-tabs-with-material-design.html

**Comment by jaydeepw** [comment]
Thanks for the links @vivekkiran 

Material tabs has been implemented. Check the changelog here.
https://github.com/jaydeepw/poly-picker#v1013-snapshot

Also please help me with testing the new SNAPSHOT build. More information about testing here.
https://github.com/jaydeepw/poly-picker#testing-snapshot-build

**Comment by jaydeepw** [comment]
Duplicate issue #23
