### ISSUE TITLE
Snapshot build, can not download ?

### ISSUE THREAD

**Issue by cubehead** [jaydeepw/poly-picker#45]

**Comment by jaydeepw** [comment]
Hi @cubehead can you tell me what error it throws?

**Comment by cubehead** [comment]
https://oss.sonatype.org/content/repositories/snapshots/net/the4thdimension/poly-picker/
there is no data. only xml.

**Comment by jaydeepw** [comment]
Ahh... let me see. I have been using it in one of my development projects and it works.

**Comment by jaydeepw** [comment]
Hey, here is the correct way of downloading the snapshot. You are using wrong url

repositories {
    // for downloading polypicker dependency cwac-camera
    maven {
        url "https://repo.commonsware.com.s3.amazonaws.com"
    }

    // for downloading polypicker v1.0.13
    maven {
        url "https://oss.sonatype.org/content/repositories/releases/"
    }
}
