### ISSUE TITLE
how to add other language string？

### ISSUE THREAD

**Issue by cubehead** [jaydeepw/poly-picker#46]
i18n support, please.

**Comment by jaydeepw** [comment]
Here are some details how to localize in Android. I would really get things ready for you to just add localized strings but right now I am working in office and got a lot of work to finish.

http://developer.android.com/guide/topics/resources/localization.html#using-framework

**Comment by jaydeepw** [comment]
Basically if you want to, for example, localize for french language, add a directory named values-fr in res/ and copy the strings.xml file to it. Change all the readable English default strings to French and you are done. Send me a pull request.
