### ISSUE TITLE
Error:Failed to resolve: com.commonsware.cwac:camera:0.6.10

### ISSUE THREAD

**Issue by pasaneramusugoda** [jaydeepw/poly-picker#56]
First of all I really liked your library.
But when I try to compile, I'm getting above error. Please help on this.
My specs:
Compile SDK: API22
Min SDK: API16
Target SDK: API22

**Comment by harshvishu** [comment]
I think the problem is with  library 'com.commonsware.cwac:camera:0.6.+'

**Comment by jaydeepw** [comment]
The problem is that people dont read the documentation carefully. Cwac camera is hosted on S3 and needs specific url to be added to fetch .aar from.

Please find how to add it here.

https://github.com/jaydeepw/poly-picker#download

**Comment by rondelserrano** [comment]
Hi do you have a workspace file which I can run this source from Eclipse ADT?

**Comment by jaydeepw** [comment]
Sorry, I dont. Never touched Eclipse after Jan '15

**Comment by rondelserrano** [comment]
So what are you using then? Thanks :)

**Comment by jaydeepw** [comment]
Android Studio ofcourse.

**Comment by rsv355** [comment]
Use this
 repositories {
        maven { url 'https://repo.commonsware.com.s3.amazonaws.com' }
        maven { url 'https://jitpack.io' }    
        maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
    }

**Comment by kenglang** [comment]
@rsv355 working for me, thank you !

**Comment by Akshay602** [comment]
it worked for me thanks

**Comment by fukemy** [comment]
care your ass. Nigga thank you

**Comment by Sathriyansiva** [comment]
https://github.com/jaydeepw/poly-picker#download
that one only shows that error
Error:Failed to resolve: com.commonsware.cwac:camera:0.6.10

**Comment by sanketwebbions** [comment]
Failed to resolve: com.github.jaydeepw:poly-picker:1.0.23

**Comment by PlotHoles** [comment]
Error:(48, 13) Failed to resolve: com.github.jaydeepw:poly-picker:1.0.23

**Comment by ryanzulham** [comment]
My error
Error:(89, 13) Failed to resolve: com.github.jaydeepw:poly-picker:1.0.23
help me please

**Comment by vvbhandare** [comment]
@rsv355 Perfect solution. Better if you could provide source where you got to know this.

**Comment by jkisanga** [comment]
I have the same problem, in which gradle should I add 
maven { url 'https://repo.commonsware.com.s3.amazonaws.com' }
maven { url 'https://jitpack.io' }
maven { url "https://s3.amazonaws.com/repo.commonsware.com" }

Project levele or app?

**Comment by rsv355** [comment]
@jkisanga @ You have to add in app level gradle file

**Comment by jkisanga** [comment]
this is my gradle app level and am still getting  Failed to resolve: com.github.jaydeepw:poly-picker:1.0.23

Please help


android {
    compileSdkVersion 25
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven { url 'https://repo.commonsware.com.s3.amazonaws.com' }
    maven { url 'https://jitpack.io' }
    maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })


//This is the  one bring error
    compile 'com.github.jaydeepw:poly-picker:1.0.23'



    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-vector-drawable:25.3.1'
    compile 'com.squareup.retrofit2:retrofit:2.0.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:cardview-v7:25.3.1'
}
