### ISSUE TITLE
Use this library with Fragments

### ISSUE THREAD

**Issue by cbranca** [jaydeepw/poly-picker#57]
Hello, I want to use this library but I'm new to Android programming so I didn't understand well how to use it with fragments.
I am developing an app that for now has only one activity (Navigation Drawer) and fragments (other pages).
I tried to integrate this library, trying to understand the code from the PolyPickerDemo in this repository, but when I click on the button Pick image it crashes.

Can someone help me with an example? If someone want to help me I will post the code of the fragment I made.

**Comment by jaydeepw** [comment]
Please post the crash log here and lets see if the crash is in the library or outside it.

**Comment by cbranca** [comment]
Hi @jaydeepw, today I was trying the code to show here, and fortunately started working. I passed two days trying to make it work before open this issue. So the problem is solved.
But there is a thing I want to report: I'm using the stable version of the library and I can't import "nl.changer.polypicker.Config", so I can't use the getNimages() method. Is this Config class only in the snapshot version of the library?
However thank you very much for this fantastic library :)

**Comment by jaydeepw** [comment]
Thanks for using the library.

Yes,  the feature with config is available only for Snapshot builds for now.
