### ISSUE TITLE
Crash when taking hi-res photos

### ISSUE THREAD

**Issue by wjwarren** [jaydeepw/poly-picker#58]
**Steps to reproduce**

1. Use a device with a hi-res camera, like the Samsung Galaxy S5 which has a 16MP camera.
1. Start the demo.
1. Take a photo.

**Actual result**

1. The demo crashes.

**Expected result**

1. The photo is saved.

**Notes**
Lib version: 1.0.11.

For some reason the demo app does not always capture images in high resolution.

Stacktrace of crash
```bash
java.lang.NullPointerException: uriString
    at android.net.Uri$StringUri.<init>(Uri.java:467)
    at android.net.Uri$StringUri.<init>(Uri.java:457)
    at android.net.Uri.parse(Uri.java:429)
    at nl.changer.polypicker.CwacCameraFragment$DemoCameraHost.saveImage(CwacCameraFragment.java:138)
    at com.commonsware.cwac.camera.ImageCleanupTask.run(ImageCleanupTask.java:133)
```

Looking at the `CwacCameraFragment` class' `saveImage()` [method](https://github.com/jaydeepw/poly-picker/blob/c7d8f0e047e7fdc10a53c39312b3c216ce32dff1/PolyPicker/app/src/main/java/nl/changer/polypicker/CwacCameraFragment.java#L136), I do see that there is no null checking for the result of calling `MediaStore.Images.Media.insertImage(...)`. According to the [Android docs](https://developer.android.com/reference/android/provider/MediaStore.Images.Media.html#insertImage(android.content.ContentResolver, android.graphics.Bitmap, java.lang.String, java.lang.String)) this method could return `null`.

> The URL to the newly created image, or null if the image failed to be stored for any reason.

**Comment by wjwarren** [comment]
@jaydeepw I pushed a fix for this issue on my fork of this lib. Please let me know if the changeset looks good and I'll create a pull request.

**Comment by jaydeepw** [comment]
Wow. Thats great. Thanks for the fix. Please pull from master too, if not already.  I cannot find your changelog. But as this is a simple null check, just submit the PR and I shall merge to master.

**Comment by wjwarren** [comment]
Hey, this is the changeset: https://github.com/wjwarren/poly-picker/commit/674e51f047e474d118180cdb6d39e86f829a216c

I created a new branch from the v1.0.11 tag because I didn't want to add snapshot code to my production app.

If you want I can apply the patch to the master branch and create a pull request from there.

**Comment by jaydeepw** [comment]
Looks good. Apply the patch.

**Comment by wjwarren** [comment]
Actually, what about user feedback? Right now it will just fail silently.

Perhaps show a Toast when the image can't be saved?

**Comment by jaydeepw** [comment]
Yes, this thought popped in my mind too when I read the changelog but thought that would be more to ask to you. Showing a Toast is okay in this case. Show it when the system returns the path == null

**Comment by wjwarren** [comment]
Cool, will send a pull request your way soon :smile:

**Comment by wjwarren** [comment]
Here it is: https://github.com/jaydeepw/poly-picker/pull/59
