### ISSUE TITLE
can not build gradle when using 'net.the4thdimension:poly-picker:1.0.13-SNAPSHOT' dependency 

### ISSUE THREAD

**Issue by pawarlalit29** [jaydeepw/poly-picker#60]
Error:(70, 13) Failed to resolve: net.the4thdimension:poly-picker:1.0.13-SNAPSHOT

**Comment by jaydeepw** [comment]
Check this

repositories {
    // for downloading Polypicker dependency cwac-camera
    maven {
        url "https://repo.commonsware.com.s3.amazonaws.com"
    }

    // for downloading polypicker v1.0.13-SNAPSHOT
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.+'
    // and other dependencies

    // PolyPicker dependency.
    compile 'net.the4thdimension:poly-picker:1.0.13-SNAPSHOT'
}

**Comment by jaydeepw** [comment]
This is mentioned in the docs. Please refer.

**Comment by pawarlalit29** [comment]
still facing issue  Failed to resolve: net.the4thdimension:poly-picker:1.0.13-SNAPSHOT

**Comment by pawarlalit29** [comment]
work in these dependency 'compile 'net.the4thdimension:poly-picker:1.0.11''
not on 1.0.13-SNAPSHOT

**Comment by pawarlalit29** [comment]
thanks for the reply i found that solution in #45 
use - compile 'net.the4thdimension:poly-picker:1.0.13' - this dependency,
there is no data in your snapshot directory 

 // for downloading polypicker v1.0.13
    maven {
        url "https://oss.sonatype.org/content/repositories/releases/"
    }
