### ISSUE TITLE
Conflicts with existing FAB

### ISSUE THREAD

**Issue by kevindesai777** [jaydeepw/poly-picker#67]
After compiling this library existing FAB turned square and it's color changed. On removing the library, FAB returned back to normal.

**Comment by jaydeepw** [comment]
Which library are you using in your app to show FAB?

**Comment by kevindesai777** [comment]
Android Design Library.

**Comment by jaydeepw** [comment]
version?

**Comment by kevindesai777** [comment]
Just one version exists. 22.2.0

**Comment by jaydeepw** [comment]
Ohh OK. This uses 22.0.0. That is the issue.

compile 'net.the4thdimension:poly-picker:1.0.14' {
  exclude group: com.android.support', name: 'appcompat-v7', version: 'appcompat-v7'
 }

Something like this to escape the dependency that I have added and use the one you have added.
It is called removing transitive dependency. If this doesnt work, just get the module in you app and remove dependencies.

**Comment by kevindesai777** [comment]
There is some error.
String end expected is what Android Studio gives.

**Comment by jaydeepw** [comment]
exclude group: 'com.android.support', name: 'appcompat-v7', version: 'appcompat-v7'

**Comment by kevindesai777** [comment]
Still not working

Error:(46, 0) Gradle DSL method not found: 'net.the4thdimension:poly-picker:1.0.14()'
Possible causes:<ul><li>The project 'Moments' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by jaydeepw** [comment]
Why are there braces '()' next to the version number?

**Comment by kevindesai777** [comment]
That's what the error shows up like. 
Support library got an update, now up to version 22.2.1.
Can you update your library?

**Comment by jaydeepw** [comment]
Sorry but updating master is not straight forward, otherwise I would have dont that thsi weekend.
The directory structure has changed in develop and merging that with master needs some testing and time. I will try earliest to get it done and then comment back here.

**Comment by kevindesai777** [comment]
Alright! Will wait for it

**Comment by jaydeepw** [comment]
I just checked with gradle please, it shows me the latest version is "compile 'com.android.support:appcompat-v7:22.2.0'" which is the same version I am using and it works in the same app.

**Comment by jaydeepw** [comment]
Hi Kevin,
I am here again. Can you please revisit the download section of the library. I have just recently updated it.
https://github.com/jaydeepw/poly-picker#download

I made 2 changes, first update readme with correct dependency string and secondly, also add the jitpack as a repository url in the repositories section of build.gradle. Please make sure that version number is now, 'v1.0.14'

**Comment by nimitsolanki** [comment]
Hi Jaydeep, 

I'm using v1.0.14 and facing same issue. FAB turned to square. Do we have any update on this issue ?

**Comment by jaydeepw** [comment]
Ahh,,, sorry man. No idea about it. The FAB shows correct for me on both, Lollipop and lesser API devices.

**Comment by kevindesai777** [comment]
![capture](https://cloud.githubusercontent.com/assets/5458209/8794335/70789e9e-2fa0-11e5-933f-6a544bfb003b.PNG)
Still the same issue!

**Comment by nimitsolanki** [comment]
Guys, Do we have any work around for this issue ?

**Comment by kevindesai777** [comment]
@jaydeepw I am not having issues with the FAB in the Camera fragment. Another FAB that I use in my project turned to square.

**Comment by kevindesai777** [comment]
@nimitsolanki Not currently

**Comment by jaydeepw** [comment]
@kevindesai777 that is coz camera fragment is using 3rd party FAB right now. I tried putting new FAB from design support in polypicker but that made FAB square on Lollipop, working well on <21. So I decided to continue with 3rd party FAB. However, Chris Banes cheesesquare works well on both, >=21 and <21 https://github.com/chrisbanes/cheesesquare

**Comment by jaydeepw** [comment]
I am not able to figure out what is being done wrong when using FAB from design support. Let me know if you guys are able to figure out.

**Comment by kevindesai777** [comment]
In the Android Design Library v22.2.0, the FAB had a couple of issues. If you put app:borderWidth="0dp" the square will turn to round. Also a couple of days back they updated the support library to version 22.2.1 which fixes that issue. 

https://www.reddit.com/r/androiddev/comments/3dnibt/support_library_2221_released/

**Comment by jaydeepw** [comment]
AFA I recall, I had tried adding app:borderWidth=0dp and that didnt work in my case. Maybe I will try that again and then if everything looks fine, will bring PP with FAB to life. :)

**Comment by nimitsolanki** [comment]
app:borderWidth="0dp" didn't work. What about adding updated support library. ?? any luck ?

**Comment by kevindesai777** [comment]
I'll give it a try. Will submit a pull request if it works!

**Comment by jaydeepw** [comment]
@nimitsolanki I tried that the day it was released, no change!!

**Comment by nimitsolanki** [comment]
@jaydeepw and @kevindesai777 Any suggestion for similar multiple image picker library ?

**Comment by jaydeepw** [comment]
@nimitsolanki you can check where I got inspiration from. I am not sure if they are being maintained or developer anymore. Why dont you just clone this repo and try to fix the issues you are having and also submit a PR. I am sure there is something minor that has been done wrong in this version.

**Comment by nimitsolanki** [comment]
Sure. I'll try to fix it and will submit a PR. Currently I'm running out of time, really want this kind of feature.
